# ============================================================
# Resume Generator — Professional PDF using fpdf2 (open-source)
# No external API required
# ============================================================

from fpdf import FPDF
from fpdf.enums import XPos, YPos


# Brand colours
PURPLE   = (124, 111, 247)
BLUE     = (90, 140, 248)
DARK_BG  = (15,  15,  30)
GREY_TXT = (100, 100, 130)
WHITE    = (255, 255, 255)
LIGHT    = (240, 240, 255)
GREEN    = (52,  211, 153)


class ResumePDF(FPDF):
    def __init__(self, candidate: dict):
        super().__init__()
        self.candidate = candidate
        self.set_margins(0, 0, 0)
        self.set_auto_page_break(auto=True, margin=15)

    # ── Helpers ───────────────────────────────────────────────
    def _rgb(self, triplet):
        return triplet[0], triplet[1], triplet[2]

    def _section_title(self, title: str):
        self.ln(4)
        self.set_fill_color(*PURPLE)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 9)
        self.set_x(15)
        self.cell(180, 7, f"  {title.upper()}", fill=True,
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(2)

    def _bullet(self, text: str, indent: int = 20):
        self.set_x(indent)
        self.set_text_color(*GREY_TXT)
        self.set_font("Helvetica", "", 9)
        self.multi_cell(175, 5, f">>  {text}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def _kv(self, key: str, value: str):
        self.set_x(20)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*PURPLE)
        self.cell(35, 5, key + ":", new_x=XPos.RIGHT, new_y=YPos.TOP)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(40, 40, 60)
        self.multi_cell(140, 5, value, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # ── Header ────────────────────────────────────────────────
    def header(self):
        c = self.candidate
        # Purple gradient banner
        self.set_fill_color(*DARK_BG)
        self.rect(0, 0, 210, 48, "F")

        # Accent stripe
        self.set_fill_color(*PURPLE)
        self.rect(0, 44, 210, 4, "F")

        # Name
        self.set_xy(15, 10)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 22)
        self.cell(0, 10, c.get("name", "Candidate"),
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Contact row
        self.set_xy(15, 28)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*LIGHT)
        email   = c.get("email", "")
        loc     = c.get("location", "")
        emp     = c.get("employment_type", "Full-time")
        exp     = c.get("experience_years", 0)
        contact = f"{email}   |   {loc}   |   {emp}   |   {exp} yrs experience"
        self.cell(0, 5, contact, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Portfolio
        portfolio = c.get("portfolio_url", "")
        if portfolio:
            self.set_xy(15, 35)
            self.set_font("Helvetica", "U", 9)
            self.set_text_color(*BLUE)
            self.cell(0, 5, portfolio, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        self.set_y(54)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*GREY_TXT)
        self.cell(0, 5,
                  "Generated by TalentScout AI  |  Catalyst Hackathon 2026  |  Open-Source Resume Intelligence",
                  align="C")


def generate_resume_pdf(candidate: dict) -> bytes:
    """Generate a professional PDF resume for a candidate. Returns raw bytes."""
    pdf = ResumePDF(candidate)
    pdf.add_page()

    c = candidate
    edu  = c.get("education", {})
    proj = c.get("projects", [])
    oss  = c.get("open_source_contributions", [])
    sigs = c.get("engagement_signals", {})

    # ── Education ─────────────────────────────────────────────
    pdf._section_title("Education")
    degree  = edu.get("degree", "Degree not specified")
    inst    = edu.get("institution", "Institution not specified")
    tier    = edu.get("tier", 3)
    tier_lbl = {1: "Tier-1 (IIT/IIM/NIT level)", 2: "Tier-2 Institution", 3: "Tier-3 Institution"}.get(tier, "Institution")
    pdf._kv("Degree", degree)
    pdf._kv("Institution", f"{inst}  [{tier_lbl}]")

    # ── Technical Skills ──────────────────────────────────────
    pdf._section_title("Technical Skills")
    skills = c.get("skills", [])
    chunks = [skills[i:i+6] for i in range(0, len(skills), 6)]
    for chunk in chunks:
        pdf._bullet("  |  ".join(chunk))

    # ── Work Experience ───────────────────────────────────────
    pdf._section_title("Work Experience")
    exp = c.get("experience_years", 0)
    emp = c.get("employment_type", "Full-time")
    pdf._kv("Total Experience", f"{exp} years  ({emp})")
    pdf._kv("Location", c.get("location", ""))

    # ── Projects ──────────────────────────────────────────────
    if proj:
        pdf._section_title("Projects & Achievements")
        for p in proj:
            pdf.ln(1)
            pdf.set_x(20)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*PURPLE)
            tag = "  [Real-World]" if p.get("is_real_world") else "  [Academic]"
            pdf.cell(0, 5, p.get("name", "Project") + tag,
                     new_x=XPos.LMARGIN, new_y=YPos.NEXT)

            desc = p.get("description", "")
            if desc:
                pdf._bullet(desc, indent=25)
            impact = p.get("impact", "")
            if impact:
                pdf.set_x(25)
                pdf.set_font("Helvetica", "BI", 8)
                pdf.set_text_color(*GREEN)
                pdf.cell(0, 5, f"Impact: {impact}",
                         new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # ── Open Source ───────────────────────────────────────────
    if oss:
        pdf._section_title("Open-Source Contributions")
        pdf._bullet("Contributed to: " + ", ".join(oss))

    # ── Engagement & Certifications ───────────────────────────
    pdf._section_title("Engagement & Assessments")
    signal_labels = {
        "applied_to_job":           "Applied to the job listing",
        "responded_to_outreach":    "Responded to recruiter outreach",
        "submitted_video_demo":     "Submitted video demo / introduction",
        "completed_assessment":     "Completed AI-powered assessment",
        "passed_assessment":        "Passed all assessment sections",
        "interview_scheduled":      "AI interview completed & scheduled",
    }
    any_signal = False
    for key, label in signal_labels.items():
        if sigs.get(key):
            pdf._bullet(label)
            any_signal = True
    if not any_signal:
        pdf._bullet("No engagement activity recorded yet")

    # ── Links ─────────────────────────────────────────────────
    links = []
    if c.get("portfolio_url"):
        links.append(("Portfolio / GitHub", c["portfolio_url"]))
    if c.get("resume_url"):
        links.append(("Resume Link", c["resume_url"]))
    if c.get("video_intro_url"):
        links.append(("Video Introduction", c["video_intro_url"]))

    if links:
        pdf._section_title("Links & Portfolio")
        for label, url in links:
            pdf.set_x(20)
            pdf.set_font("Helvetica", "U", 9)
            pdf.set_text_color(*BLUE)
            pdf.cell(40, 5, label + ":", new_x=XPos.RIGHT, new_y=YPos.TOP)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(40, 40, 60)
            pdf.cell(140, 5, url, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    return bytes(pdf.output())
